apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-production.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - args:
        - sh
        - -c
        - /wait && python worker.py
        env:
        - name: APP_SETTINGS
          value: config.ProductionConfig
        - name: DATABASE_URL
          value: postgresql://wordcount_dbadmin:@db/wordcount_dev
        - name: REDISTOGO_URL
          value: redis://redis:6379
        - name: WAIT_BEFORE_HOSTS
          value: "20"
        - name: WAIT_HOSTS
          value: redis:6379, db:5432
        image: griggheo/flask-by-example:production_v2
        name: worker
        resources: {}
      restartPolicy: Always
status: {}
